nmn/react-timeago

timeago.js

Sometimes it's helpful to see the original date using the title attribute like in the screenshot below:

Add date prop as title attribute

---

timeago.js

Not clearing the timeout was causing build scripts to hang as we were generating after we included readt-timeago in one of our components even after we had unmounted the components. Clearing the timeout as the component is unmounted fixes this issue

Clear the timeout when the component is unmounted

---

timeago.js

One considerable usability downside of relative timestamps is taking control from the user.
`title` attribute is a small step to improve that. It’s not perfect, but it has effectively no downsides.
The format is ISO `2015-01-01 01:23` to avoid having to deal with localizations,
and yet provide a sensible default.
In case the date provided is already a string, it’s likely to be better for the user.
For an example the time portion might be missing. Since the `Date` object
unfortunately, does not represent that, we would have `00:00` in the end.
Using the input string as is is better in such scenarios.

Add a title attribute

---

timeago.js

Per documentation, minPeriod and maxPeriod are intended to use seconds by default rather than milliseconds.  Also referenced in #17.  This PR updates the code to reflect that.

Fix minPeriod and maxPeriod to use seconds rather than milliseconds

---

src/index.js

The typo is causing timers to continue even when the component is unmounted.

Typo in willUnmount lifecycle hook

---

src/index.js

Fixes react-timeago in IE11 and anything else which doesn't implement `Object.assign()` natively
This should also close #33

Use object spread syntax instead of Object.assign()

---

package.json
src/index.js

Fixes IE11 and anything else which doesn't implement Object.assign() natively

Avoid use of Object.assign() and drop unused object-assign dependency

---

.gitignore
package.json
src/formatters/buildFormatter.js
test/index.js

The first commit is a quick fix of the undefined word separator to follow the [jquery-timeago#L114-L115](https://github.com/rmm5t/jquery-timeago/blob/master/jquery.timeago.js#L114-L115). Now an empty string will not be automatically transform to a space character.
Also, there is a fix on the week bug mentioned in #44, it still need test though.

Handle undefined word separator, and fix #44, #49

---

README.md
package.json
src/index.js

Proposed addition with README.md updated.

Issue #62: Default formatter to be exposed as a `next()` call

---

src/defaultFormatter.js

Why:
* Default formatter was output pluralized units when it should be singluar

fix default formatter

---

src/dateParser.js
src/index.js

As described in #74, `react-timeago` renders `` on Safari and Safari on iOS when fed `ISO 8601` dates containing offsets sans colon, e.g. `2017-03-05T08:54:30+0100`. The ISO specification allows for 4 different permutations.
````
<time>Z
<time>±hh:mm
<time>±hhmm
<time>±hh
````
Safari returns `null` for `new Date(isoDateWithoutColon)`. While there seem to be many ways to work around this, `Date.UTC` is particularly convenient. May need some more testing.

Work around Safari date parser silent fail on particular TZ offsets 

---

src/index.js

Flow has (correctly) identified this parameter as being unused.
```
node_modules/react-timeago/lib/index.js.flow:195
195:     const nextFormatter = defaultFormatter.bind(null, value, unit, suffix, then)
^^^^ unused function argument
v--------------------------------------------------------------------------------
3: export default function defaultFormatter (value: number, unit: string, suffix: string): string {
4:   if (value !== 1) {
5:     unit += 's'
...:
8: }
^ function expects no more than 3 arguments. See: node_modules/react-timeago/lib/defaultFormatter.js.flow:3
```

remove "then" parameter from defaultFormatter bind

---

src/index.js

Added exporting of the unit constants MINUTE, DAY, WEEK, etc. as named exports for re-use inside of client code, especially useful in custom formatters, or general re-use by dependent projects. (Otherwise these constants have to be redefined in each consuming project).
This could then be imported like so:
import TimeAgo, { HOUR, MINUTE, SECOND } from 'react-timeago';
Because these are constants, the values cannot be redefined and cause unintended behavior in the application. This is not a breaking change: existing consumers would notice no changes since there are currently no named exports. I am open to discussion on this pull request, because I think there ought to be *some* re-use provided to consumers in their custom formatters. Another option would be to export Unit or something like …

[Semver-Minor] Adds named exports for UNIT constants

---

src/index.js

componentDidUpdate is calling tick, which creates a new timeout without clearing any existing ones.

Fix #118, losing reference to timers.

---

src/language-strings/tr.js

Hello, thank you for creating this library. It's really useful and well made. During my usage with the Turkish language, I found that some fields in the language string is missing or incorrect. Here you can see that I updated them. 
In seconds it was; '1 dakikadan' which means, from one minute. First added the second field with value '1 saniye' which means one second in Turkish. After that, I modified the seconds field accordingly.
Lastly, I added the value 'sonra' to the suffixFromNow field.

Fix tr language

---

src/index.js

For dates older than a day, and where `minPeriod` was set, the component updated every `minPeriod`.
With this update, dates older than a day are always decided by the `maxPeriod` option.

Fix update period for dates older than a day

---

package.json

npm7 now requires explicit dependencies, so without this change, those on the latest npm will have broken builds

React 17 support

---

src/index.js

Fix for issue #154. useEffect dependencies updated to include [date]. This prevents an issue where my nested <TimeAgo /> component doesn't update on its own.
Thank you to Brennan for the solution (https://github.com/nmn/react-timeago/issues/154#issuecomment-829718495).

Fix for issue #154

---

CHANGELOG.md
README.md
package.json
src/formatters/buildFormatter.js
src/index.js

Love this project @nmn, thanks for authoring it! Was using it and wanted to contribute a couple small updates.
Notably:
- Moved `CHANGELOG` to its own file
- Fixed the `epochMilliseconds` argument in docs, and in code to add two `lls`
- Misc. formatting 
- Alphabetized npm scripts

Fix epochMilliseconds argument; minor README updates

---

package.json
src/index.js

If the date is more than a week away, then the refresh period would be set to `Infinity`. This gets passed to a `setTimeout`, which fires immediately causing a refresh loop, which in my instance resulted in 100% cpu usage.
It could also be the cause of https://github.com/nmn/react-timeago/issues/160
The code already does a true-y check on period before issuing the setTimeout, this patch also explicitly checks for Infinity to ensure that the timeout doesn't fire
Infinite timeouts are a bit of a js quirk that really don't behave as expected - https://github.com/denysdovhan/wtfjs#an-infinite-timeout

Fix refresh creating an infinite timeout loop

---

src/index.js

Fixes https://github.com/nmn/react-timeago/issues/160
I noticed the https://github.com/nmn/react-timeago/issues/160 memory leak issue as well (i.e. it's reproducible in the simple example), but it was unfortunately not fixed with https://github.com/nmn/react-timeago/pull/161.
This makes two changes, which seems to mitigate the issue:
1. Update the `setTimeout` callback to just bump a (new) `timeNow` state. I think passing a reference to the `tick` function was ultimately causing the memory leak, and this approach also removes the need for a "force update".
2. Update the default `now` argument to a `Date.now` reference (as opposed to a new closure). This was getting redefined on every render and causing duplicate effect calls, which was contributing to the issue.

Fix memory leak

---

src/language-strings/en-fuzzy-short.js
src/language-strings/en-fuzzy.js

```js
import TimeAgo from 'react-timeago'
import fuzzyStrings from 'react-timeago/lib/language-strings/en-fuzzy'
import buildFormatter from 'react-timeago/lib/formatters/buildFormatter'
const formatter = buildFormatter(fuzzyStrings)
// "a moment ago" -> "about a minute ago" -> "2 minutes ago" -> ...
<TimeAgo date={Date.now()} formatter={formatter} />
```
```js
import TimeAgo from 'react-timeago'
import fuzzyShortStrings from 'react-timeago/lib/language-strings/en-fuzzy-short' // "just now"
import buildFormatter from 'react-timeago/lib/formatters/buildFormatter'
const formatter = buildFormatter(fuzzyShortStrings)
// "just now" -> "1m" -> "2m" -> ...
<TimeAgo date={Date.now()} formatter={formatter} />
```
---
see: #172

support for fuzzy intervals

---

src/index.js

The `now` function is a dependency in the `useEffect`; as a result, whenever `now` changes, the previous timeout gets cleared and a new timeout gets queued.
The problem with this is, since the default value of `now` was within the component: `now = () => Date.now()`, if the `TimeAgo` component ever re-renders, the `now` function would end up with a new function reference, and the `useEffect` would be triggered.
In my use case, `TimeAgo` was a child component of a parent that would re-render every ~5 seconds. 
- When the date is less than 1 minute ago, the refresh period would be every second, so the timeouts would always trigger as expected
- However, when the date is greater than 1 minute ago, the refresh period becomes 60 seconds, but since my component was re-rendering every ~5 …

Fix time not updating when period is longer than component re-render time

---

src/language-strings/ko.js

https://github.com/nmn/react-timeago/pull/60 changed "1분" to "방금" which is unfortunately only half correct. ("1분" means "1 minute" as opposed to "less than a minute", which I imagine was why the new translation was suggested.)
For `seconds` + `suffixAgo`, it's fine.
"방금 전" = "a moment ago"
For `seconds` + `suffixFromNow`, it is wrong.
"방금 후" does not make sense.
"몇 초" means "several seconds", works with both suffixes, and sounds natural for native speakers. Variants of direct translations of "less than a minute" were considered and are not technically wrong (e.g., "1분 미만 전"), but they sound very awkward.

Fix Korean "seconds" string

---

package.json

Quick fix for issue https://github.com/nmn/react-timeago/issues/213 by updating the `exports` field in `package.json` allowing direct import of language-strings and formatter files
This restores compatibility for projects relying on these internal modules before the exports field was introduced.

Package.json : Allow access to language-strings and formatters files

---

package.json

Fixes #213 
- Improves the exports declaration to correctly handle both CJS and ESM exports.
- Still need to check if I need to change the file extension for the files under `es6` to `.mjs`. (Help appreciated)

fix: fix exports in package.json

---

CHANGELOG.md
package.json
src/index.js

Fixes #230 
This PR exports `Formatter`, `Unit` and `Suffix` types which were present in v7. Now you can do this again:
```typescript
import type { Formatter, Suffix, Unit } from 'react-timeago';
const myCustomFormatter: Formatter = (
value: number,
unit: Unit,
suffix: Suffix,
epochMilliseconds: number,
nextFormatter: Formatter,
now: () => number,
) => {
if (suffix === 'from now' || unit === 'second') return 'just now';
if (nextFormatter) return nextFormatter(value, unit, suffix, epochMilliseconds, nextFormatter, now);
return '';
};
```

Export Formatter, Unit and Suffix types
